package br.edu.ifnmg.poo.opala;

import br.edu.ifnmg.poo.credential.Credential;
import br.edu.ifnmg.poo.driver.Driver;
import br.edu.ifnmg.poo.driver.DriverDAO;
import br.edu.ifnmg.poo.parkingSpace.ParkingSpace;
import br.edu.ifnmg.poo.parkingSpace.ParkingSpaceDAO;
import br.edu.ifnmg.poo.repository.DbConnection;
import br.edu.ifnmg.poo.vehicle.Vehicle;
import br.edu.ifnmg.poo.vehicle.VehicleDAO;
import com.formdev.flatlaf.util.SystemInfo;
import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author bvan &lt;Bruno Vinícius at ifnmg&gt;
 */
public class MainScreen extends javax.swing.JFrame {

    private static MainScreen instance;
    private final CardLayout cardMainScreen;
    private JButton lastClickedButton;

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        cardMainScreen = (CardLayout) pnlMain.getLayout();

        //Transparent title bar on macos
//        if( SystemInfo.isMacFullWindowContentSupported )
//            getRootPane().putClientProperty( "apple.awt.transparentTitleBar", true );
        if (SystemInfo.isMacFullWindowContentSupported) {
            getRootPane().putClientProperty("apple.awt.fullWindowContent", true);
            getRootPane().putClientProperty("apple.awt.transparentTitleBar", true);
        }

        DefaultTableModel model = (DefaultTableModel) tableDriver.getModel();
        tableDriver.setRowSorter(new TableRowSorter(model));
        FillTable(tableDriver, "selct * from vehicle");
    }

    public MainScreen(Credential credential) {
        this();
        switch (credential.getType()) {
            case ADMIN -> {
                this.btnHome.setEnabled(true);
                this.btnPayment.setEnabled(true);
                this.btnSubscriber.setEnabled(true);
                this.btnUser.setEnabled(true);
            }
            case OPERATOR -> {
                this.btnHome.setEnabled(true);
                this.btnPayment.setEnabled(true);
                this.btnSubscriber.setEnabled(true);
            }
            case SUBSCRIBER -> {
                btnRelatorioActionPerformed(null);
            }
        }
        this.setTitle(this.getTitle() + " - " + credential.getUser().getName());
    }

    public static MainScreen getInstance() {
        if (instance == null) {
            instance = new MainScreen();
        }
        return instance;
    }

    private void changeColorButton(JButton button) {
        if (lastClickedButton != null) {
            lastClickedButton.setBackground(null);
        }
        button.setBackground(Color.decode("#0085FF"));
        lastClickedButton = button;
    }

    public void FillTable(JTable table, String Query) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        VehicleDAO vDao = new VehicleDAO();
        
        List<Vehicle> vList = vDao.findAll();
        
        for (Vehicle v : vList) {
            model.addRow(new Object[] {
                v.getId(),
                v.getLicensePlate()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnSubscriber = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlMain = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        EntradaDeVeiculosjPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtVaga = new javax.swing.JTextField();
        cBplace = new javax.swing.JComboBox<>();
        lblEntrada = new javax.swing.JLabel();
        txtCheckInTime = new javax.swing.JTextField();
        txtCheckInDate = new javax.swing.JTextField();
        txtSaida = new javax.swing.JLabel();
        txtCheckOutTime = new javax.swing.JTextField();
        txtCheckOutDate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblNote = new javax.swing.JLabel();
        FieldNotes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EstacionamentojPanel = new javax.swing.JPanel();
        scrPaneLista = new javax.swing.JScrollPane();
        tableDriver = new javax.swing.JTable();
        lblEstacionamento = new javax.swing.JLabel();
        pnlPayment = new javax.swing.JPanel();
        lblCaixa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ValoresBotoes = new javax.swing.JPanel();
        btnTotal = new javax.swing.JButton();
        btnPix = new javax.swing.JButton();
        btnDinheiro = new javax.swing.JButton();
        btnCartao = new javax.swing.JButton();
        scrPnLista = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        pnlRelatorio = new javax.swing.JPanel();
        btnBaixarMensal = new javax.swing.JButton();
        btnBaixarDiario = new javax.swing.JButton();
        lblRelatorio = new javax.swing.JLabel();
        pnlSubscriber = new javax.swing.JPanel();
        lblMensalista = new javax.swing.JLabel();
        scrPaneLista1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        pnlSearchIcon = new javax.swing.JPanel();
        lblSearchIcon = new javax.swing.JLabel();
        txtSearchSubscriber = new javax.swing.JTextField();
        btnAddSubscriber = new javax.swing.JButton();
        pnlUser = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        scrPaneLista2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        pnlSearchIconUser = new javax.swing.JPanel();
        lblSearchIconUser = new javax.swing.JLabel();
        txtSearchUser = new javax.swing.JTextField();
        btnAddUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OPALA Parking Lot Management System");
        setBackground(new java.awt.Color(38, 50, 56));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlMenu.setBackground(new java.awt.Color(0, 57, 99));

        btnHome.setBackground(new java.awt.Color(0, 57, 99));
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home.png"))); // NOI18N
        btnHome.setBorderPainted(false);
        btnHome.setEnabled(false);
        btnHome.setFocusPainted(false);
        btnHome.setFocusable(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnPayment.setBackground(new java.awt.Color(0, 57, 99));
        btnPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cash.png"))); // NOI18N
        btnPayment.setBorderPainted(false);
        btnPayment.setEnabled(false);
        btnPayment.setFocusPainted(false);
        btnPayment.setFocusable(false);
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        btnRelatorio.setBackground(new java.awt.Color(0, 57, 99));
        btnRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Analyze.png"))); // NOI18N
        btnRelatorio.setBorderPainted(false);
        btnRelatorio.setFocusPainted(false);
        btnRelatorio.setFocusable(false);
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        btnSubscriber.setBackground(new java.awt.Color(0, 57, 99));
        btnSubscriber.setForeground(new java.awt.Color(255, 255, 255));
        btnSubscriber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tear-Off Calendar.png"))); // NOI18N
        btnSubscriber.setBorderPainted(false);
        btnSubscriber.setEnabled(false);
        btnSubscriber.setFocusPainted(false);
        btnSubscriber.setFocusable(false);
        btnSubscriber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubscriberActionPerformed(evt);
            }
        });

        btnUser.setBackground(new java.awt.Color(0, 57, 99));
        btnUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin Settings Male.png"))); // NOI18N
        btnUser.setBorderPainted(false);
        btnUser.setEnabled(false);
        btnUser.setFocusPainted(false);
        btnUser.setFocusable(false);
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 51));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logout.png"))); // NOI18N
        btnLogout.setBorderPainted(false);
        btnLogout.setFocusPainted(false);
        btnLogout.setFocusable(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(btnPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSubscriber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubscriber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setForeground(new java.awt.Color(255, 255, 255));
        pnlMain.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(255, 255, 255));

        EntradaDeVeiculosjPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setBackground(new java.awt.Color(0, 133, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 133, 255));
        lblTitle.setText("Entrada de Veículos");

        txtPlaca.setBackground(new java.awt.Color(223, 249, 255));
        txtPlaca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPlaca.setForeground(new java.awt.Color(0, 0, 0));
        txtPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 133, 255)));
        txtPlaca.setCaretColor(new java.awt.Color(157, 230, 178));
        txtPlaca.setName("Placa:"); // NOI18N
        txtPlaca.setPreferredSize(new java.awt.Dimension(65, 25));

        txtVaga.setBackground(new java.awt.Color(223, 249, 255));
        txtVaga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtVaga.setForeground(new java.awt.Color(0, 0, 0));
        txtVaga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 133, 255), 1, true));
        txtVaga.setCaretColor(new java.awt.Color(157, 230, 178));
        txtVaga.setPreferredSize(new java.awt.Dimension(65, 25));

        cBplace.setBackground(new java.awt.Color(223, 249, 255));
        cBplace.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cBplace.setForeground(new java.awt.Color(0, 0, 0));
        cBplace.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 133, 255), 1, true));
        cBplace.setPreferredSize(new java.awt.Dimension(65, 25));
        cBplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBplaceActionPerformed(evt);
            }
        });

        lblEntrada.setBackground(new java.awt.Color(0, 133, 255));
        lblEntrada.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblEntrada.setForeground(new java.awt.Color(0, 133, 255));
        lblEntrada.setText("Entrada:");

        txtCheckInTime.setBackground(new java.awt.Color(223, 249, 255));
        txtCheckInTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCheckInTime.setForeground(new java.awt.Color(0, 0, 0));
        txtCheckInTime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 133, 255), 1, true));
        txtCheckInTime.setCaretColor(new java.awt.Color(157, 230, 178));
        txtCheckInTime.setPreferredSize(new java.awt.Dimension(65, 25));

        txtCheckInDate.setBackground(new java.awt.Color(223, 249, 255));
        txtCheckInDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCheckInDate.setForeground(new java.awt.Color(0, 0, 0));
        txtCheckInDate.setText(" ");
        txtCheckInDate.setToolTipText("");
        txtCheckInDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 133, 255), 1, true));
        txtCheckInDate.setCaretColor(new java.awt.Color(157, 230, 178));
        txtCheckInDate.setPreferredSize(new java.awt.Dimension(65, 25));
        txtCheckInDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckInDateActionPerformed(evt);
            }
        });

        txtSaida.setBackground(new java.awt.Color(0, 133, 255));
        txtSaida.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtSaida.setForeground(new java.awt.Color(0, 133, 255));
        txtSaida.setText("Saida:");

        txtCheckOutTime.setBackground(new java.awt.Color(223, 249, 255));
        txtCheckOutTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCheckOutTime.setForeground(new java.awt.Color(0, 0, 0));
        txtCheckOutTime.setText(" ");
        txtCheckOutTime.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 133, 255), 1, true));
        txtCheckOutTime.setCaretColor(new java.awt.Color(157, 230, 178));
        txtCheckOutTime.setPreferredSize(new java.awt.Dimension(65, 25));

        txtCheckOutDate.setBackground(new java.awt.Color(223, 249, 255));
        txtCheckOutDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCheckOutDate.setForeground(new java.awt.Color(0, 0, 0));
        txtCheckOutDate.setText("  ");
        txtCheckOutDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 133, 255), 1, true));
        txtCheckOutDate.setCaretColor(new java.awt.Color(157, 230, 178));
        txtCheckOutDate.setPreferredSize(new java.awt.Dimension(65, 25));
        txtCheckOutDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckOutDateActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 133, 255));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 164, 164));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 0, 0));
        btnCancel.setText("Cancelar");

        lblNote.setBackground(new java.awt.Color(0, 133, 255));
        lblNote.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNote.setForeground(new java.awt.Color(0, 133, 255));
        lblNote.setText("Observações:");

        FieldNotes.setBackground(new java.awt.Color(223, 249, 255));
        FieldNotes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FieldNotes.setForeground(new java.awt.Color(0, 0, 0));
        FieldNotes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 133, 255)));
        FieldNotes.setCaretColor(new java.awt.Color(157, 230, 178));
        FieldNotes.setPreferredSize(new java.awt.Dimension(65, 25));
        FieldNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNotesActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Placa:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Vaga:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Horário:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Data:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Horário:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Data:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tipo de Veículo");

        javax.swing.GroupLayout EntradaDeVeiculosjPanelLayout = new javax.swing.GroupLayout(EntradaDeVeiculosjPanel);
        EntradaDeVeiculosjPanel.setLayout(EntradaDeVeiculosjPanelLayout);
        EntradaDeVeiculosjPanelLayout.setHorizontalGroup(
            EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntradaDeVeiculosjPanelLayout.createSequentialGroup()
                .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EntradaDeVeiculosjPanelLayout.createSequentialGroup()
                        .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EntradaDeVeiculosjPanelLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EntradaDeVeiculosjPanelLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(EntradaDeVeiculosjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(EntradaDeVeiculosjPanelLayout.createSequentialGroup()
                                .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitle)
                                    .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtSaida)
                                        .addComponent(txtPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(EntradaDeVeiculosjPanelLayout.createSequentialGroup()
                                            .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtCheckOutTime, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                                    .addComponent(txtCheckInTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel5))
                                            .addGap(0, 0, 0)
                                            .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtCheckInDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtCheckOutDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel4)))
                                        .addGroup(EntradaDeVeiculosjPanelLayout.createSequentialGroup()
                                            .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(txtVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, 0)
                                            .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(cBplace, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(lblEntrada)
                                    .addComponent(lblNote)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        EntradaDeVeiculosjPanelLayout.setVerticalGroup(
            EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntradaDeVeiculosjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EntradaDeVeiculosjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cBplace, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(lblEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, 0)
                        .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCheckInTime, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtSaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, 0)
                        .addGroup(EntradaDeVeiculosjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCheckOutTime, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCheckOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(lblNote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FieldNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addGroup(EntradaDeVeiculosjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        EstacionamentojPanel.setBackground(new java.awt.Color(255, 255, 255));

        tableDriver.setBackground(new java.awt.Color(255, 255, 255));
        tableDriver.setForeground(new java.awt.Color(0, 133, 255));
        tableDriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Placa", "Vaga", "Tipo Veículo", "Horário de Entrada", "Observação"
            }
        ));
        tableDriver.setGridColor(new java.awt.Color(255, 255, 255));
        tableDriver.setSelectionBackground(new java.awt.Color(223, 249, 255));
        tableDriver.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrPaneLista.setViewportView(tableDriver);

        lblEstacionamento.setBackground(new java.awt.Color(0, 133, 255));
        lblEstacionamento.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEstacionamento.setForeground(new java.awt.Color(0, 133, 255));
        lblEstacionamento.setText("Estacionamento");

        javax.swing.GroupLayout EstacionamentojPanelLayout = new javax.swing.GroupLayout(EstacionamentojPanel);
        EstacionamentojPanel.setLayout(EstacionamentojPanelLayout);
        EstacionamentojPanelLayout.setHorizontalGroup(
            EstacionamentojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstacionamentojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EstacionamentojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstacionamento)
                    .addComponent(scrPaneLista, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE))
                .addContainerGap())
        );
        EstacionamentojPanelLayout.setVerticalGroup(
            EstacionamentojPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstacionamentojPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEstacionamento)
                .addGap(18, 18, 18)
                .addComponent(scrPaneLista))
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(EntradaDeVeiculosjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstacionamentojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstacionamentojPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EntradaDeVeiculosjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        pnlMain.add(pnlHome, "Home");

        pnlPayment.setBackground(new java.awt.Color(255, 255, 255));

        lblCaixa.setBackground(new java.awt.Color(0, 133, 255));
        lblCaixa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCaixa.setForeground(new java.awt.Color(0, 133, 255));
        lblCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaixa.setText("Movimentação");
        lblCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ValoresBotoes.setBackground(new java.awt.Color(255, 255, 255));

        btnTotal.setBackground(new java.awt.Color(0, 57, 99));
        btnTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnTotal.setForeground(new java.awt.Color(255, 255, 255));
        btnTotal.setText("TOTAL");
        btnTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 174, 255)));

        btnPix.setBackground(new java.awt.Color(0, 57, 99));
        btnPix.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPix.setForeground(new java.awt.Color(255, 255, 255));
        btnPix.setText("PIX");
        btnPix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 174, 255)));
        btnPix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPixActionPerformed(evt);
            }
        });

        btnDinheiro.setBackground(new java.awt.Color(0, 57, 99));
        btnDinheiro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDinheiro.setForeground(new java.awt.Color(255, 255, 255));
        btnDinheiro.setText("DINHEIRO");
        btnDinheiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 174, 255)));

        btnCartao.setBackground(new java.awt.Color(0, 57, 99));
        btnCartao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCartao.setForeground(new java.awt.Color(255, 255, 255));
        btnCartao.setText("CARTÃO");
        btnCartao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(87, 174, 255)));

        javax.swing.GroupLayout ValoresBotoesLayout = new javax.swing.GroupLayout(ValoresBotoes);
        ValoresBotoes.setLayout(ValoresBotoesLayout);
        ValoresBotoesLayout.setHorizontalGroup(
            ValoresBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValoresBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPix, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btnDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ValoresBotoesLayout.setVerticalGroup(
            ValoresBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ValoresBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ValoresBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPix, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tblLista.setBackground(new java.awt.Color(255, 255, 255));
        tblLista.setForeground(new java.awt.Color(138, 182, 109));
        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vaga", "Placa", "Veículo", "Horario Entrada", "Data Entrada"
            }
        ));
        tblLista.setGridColor(new java.awt.Color(255, 255, 255));
        tblLista.setSelectionBackground(new java.awt.Color(223, 249, 255));
        tblLista.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrPnLista.setViewportView(tblLista);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(ValoresBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(116, 116, 116))
            .addComponent(scrPnLista)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ValoresBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(scrPnLista, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPaymentLayout = new javax.swing.GroupLayout(pnlPayment);
        pnlPayment.setLayout(pnlPaymentLayout);
        pnlPaymentLayout.setHorizontalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(80, 80, 80))
            .addGroup(pnlPaymentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPaymentLayout.setVerticalGroup(
            pnlPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPaymentLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(118, 118, 118))
        );

        pnlMain.add(pnlPayment, "Payment");

        pnlRelatorio.setBackground(new java.awt.Color(255, 255, 255));

        btnBaixarMensal.setBackground(new java.awt.Color(0, 133, 255));
        btnBaixarMensal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBaixarMensal.setForeground(new java.awt.Color(255, 255, 255));
        btnBaixarMensal.setText("BAIXAR RELATORIO MENSAL (PDF)");

        btnBaixarDiario.setBackground(new java.awt.Color(0, 133, 255));
        btnBaixarDiario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBaixarDiario.setForeground(new java.awt.Color(255, 255, 255));
        btnBaixarDiario.setText("BAIXAR RELATORIO DIÁRIO (PDF)");

        lblRelatorio.setBackground(new java.awt.Color(138, 182, 109));
        lblRelatorio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRelatorio.setForeground(new java.awt.Color(0, 133, 255));
        lblRelatorio.setText("RELATÓRIO");

        javax.swing.GroupLayout pnlRelatorioLayout = new javax.swing.GroupLayout(pnlRelatorio);
        pnlRelatorio.setLayout(pnlRelatorioLayout);
        pnlRelatorioLayout.setHorizontalGroup(
            pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelatorioLayout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addGroup(pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBaixarDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaixarMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(305, Short.MAX_VALUE))
            .addGroup(pnlRelatorioLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblRelatorio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRelatorioLayout.setVerticalGroup(
            pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRelatorioLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(btnBaixarMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(btnBaixarDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        pnlMain.add(pnlRelatorio, "Relatorio");

        pnlSubscriber.setBackground(new java.awt.Color(255, 255, 255));

        lblMensalista.setBackground(new java.awt.Color(0, 133, 255));
        lblMensalista.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMensalista.setForeground(new java.awt.Color(0, 133, 255));
        lblMensalista.setText("MENSALISTA");

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setForeground(new java.awt.Color(0, 133, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vaga", "Placa", "Veículo", "Horario Entrada", "Data Entrada"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setSelectionBackground(new java.awt.Color(223, 249, 255));
        jTable2.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrPaneLista1.setViewportView(jTable2);

        pnlSearchIcon.setBackground(new java.awt.Color(0, 133, 255));

        lblSearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N

        javax.swing.GroupLayout pnlSearchIconLayout = new javax.swing.GroupLayout(pnlSearchIcon);
        pnlSearchIcon.setLayout(pnlSearchIconLayout);
        pnlSearchIconLayout.setHorizontalGroup(
            pnlSearchIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchIconLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblSearchIcon)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlSearchIconLayout.setVerticalGroup(
            pnlSearchIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSearchIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        txtSearchSubscriber.setBackground(new java.awt.Color(223, 249, 255));
        txtSearchSubscriber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchSubscriber.setForeground(new java.awt.Color(0, 0, 0));
        txtSearchSubscriber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 133, 255)));
        txtSearchSubscriber.setCaretColor(new java.awt.Color(157, 230, 178));
        txtSearchSubscriber.setPreferredSize(new java.awt.Dimension(65, 25));

        btnAddSubscriber.setBackground(new java.awt.Color(0, 133, 255));
        btnAddSubscriber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddSubscriber.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSubscriber.setText("ADICIONAR");

        javax.swing.GroupLayout pnlSubscriberLayout = new javax.swing.GroupLayout(pnlSubscriber);
        pnlSubscriber.setLayout(pnlSubscriberLayout);
        pnlSubscriberLayout.setHorizontalGroup(
            pnlSubscriberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubscriberLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSubscriberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrPaneLista1, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlSubscriberLayout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(txtSearchSubscriber, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlSearchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddSubscriber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlSubscriberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensalista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSubscriberLayout.setVerticalGroup(
            pnlSubscriberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubscriberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensalista, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(pnlSubscriberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSubscriberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSearchSubscriber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlSearchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddSubscriber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(scrPaneLista1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        pnlMain.add(pnlSubscriber, "Subscriber");

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));

        lblUser.setBackground(new java.awt.Color(0, 133, 255));
        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 133, 255));
        lblUser.setText("USUÁRIO");

        jTable3.setBackground(new java.awt.Color(255, 255, 255));
        jTable3.setForeground(new java.awt.Color(0, 133, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vaga", "Placa", "Veículo", "Horario Entrada", "Data Entrada"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jTable3.setSelectionBackground(new java.awt.Color(223, 249, 255));
        jTable3.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrPaneLista2.setViewportView(jTable3);

        pnlSearchIconUser.setBackground(new java.awt.Color(0, 133, 255));

        lblSearchIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Search.png"))); // NOI18N

        javax.swing.GroupLayout pnlSearchIconUserLayout = new javax.swing.GroupLayout(pnlSearchIconUser);
        pnlSearchIconUser.setLayout(pnlSearchIconUserLayout);
        pnlSearchIconUserLayout.setHorizontalGroup(
            pnlSearchIconUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchIconUserLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblSearchIconUser)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlSearchIconUserLayout.setVerticalGroup(
            pnlSearchIconUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSearchIconUser, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        txtSearchUser.setBackground(new java.awt.Color(223, 249, 255));
        txtSearchUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearchUser.setForeground(new java.awt.Color(0, 0, 0));
        txtSearchUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 133, 255)));
        txtSearchUser.setCaretColor(new java.awt.Color(157, 230, 178));
        txtSearchUser.setPreferredSize(new java.awt.Dimension(65, 25));

        btnAddUser.setBackground(new java.awt.Color(0, 133, 255));
        btnAddUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUser.setText("ADICIONAR");

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrPaneLista2, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(txtSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlSearchIconUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSearchUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlSearchIconUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(scrPaneLista2, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        pnlMain.add(pnlUser, "User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        LoginScreen.getInstance().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        cardMainScreen.show(pnlMain, "Home");
        changeColorButton(btnHome);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TODO add your handling code here:
        cardMainScreen.show(pnlMain, "Payment");
        changeColorButton(btnPayment);
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        cardMainScreen.show(pnlMain, "Relatorio");
        changeColorButton(btnRelatorio);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnSubscriberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubscriberActionPerformed
        // TODO add your handling code here:
        cardMainScreen.show(pnlMain, "Subscriber");
        changeColorButton(btnSubscriber);
    }//GEN-LAST:event_btnSubscriberActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        cardMainScreen.show(pnlMain, "User");
        changeColorButton(btnUser);
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        formWindowClosing(null);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void FieldNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNotesActionPerformed

    private void btnPixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPixActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            // TODO add your handling code here:
            Driver driver = new Driver();
            /*driver.setCredential(null);
            driver.setEmail(null);
            driver.setName(null);
            driver.setTelephone(null);*/
            driver.setTicket(1);

            ParkingSpace ps = new ParkingSpace();
            ps.setDriver(driver);
            ps.setNumber(Short.parseShort(txtVaga.getText()));
            driver.addParkingSpace(ps);
            ps.setArrivalTime(LocalDateTime.now());

            Vehicle v = new Vehicle();
            v.setNote(FieldNotes.getText());
            v.setLicensePlate(txtPlaca.getText());
            v.setDriver(driver);

            DriverDAO dDao = new DriverDAO();
            dDao.saveOrUpdate(driver);

            v.setId_driver(driver.getId());
            ps.setId_driver(driver.getId());

            VehicleDAO vDao = new VehicleDAO();
            vDao.saveOrUpdate(v);

            ParkingSpaceDAO pDao = new ParkingSpaceDAO();
            pDao.saveOrUpdate(ps);
        } catch (Exception ex) {
            Logger.getLogger(MainScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void cBplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBplaceActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cBplaceActionPerformed

    private void txtCheckOutDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckOutDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckOutDateActionPerformed

    private void txtCheckInDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckInDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckInDateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EntradaDeVeiculosjPanel;
    private javax.swing.JPanel EstacionamentojPanel;
    private javax.swing.JTextField FieldNotes;
    private javax.swing.JPanel ValoresBotoes;
    private javax.swing.JButton btnAddSubscriber;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBaixarDiario;
    private javax.swing.JButton btnBaixarMensal;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCartao;
    private javax.swing.JButton btnDinheiro;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnPix;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSubscriber;
    private javax.swing.JButton btnTotal;
    private javax.swing.JButton btnUser;
    private javax.swing.JComboBox<String> cBplace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblCaixa;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblEstacionamento;
    private javax.swing.JLabel lblMensalista;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblRelatorio;
    private javax.swing.JLabel lblSearchIcon;
    private javax.swing.JLabel lblSearchIconUser;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JPanel pnlRelatorio;
    private javax.swing.JPanel pnlSearchIcon;
    private javax.swing.JPanel pnlSearchIconUser;
    private javax.swing.JPanel pnlSubscriber;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JScrollPane scrPaneLista;
    private javax.swing.JScrollPane scrPaneLista1;
    private javax.swing.JScrollPane scrPaneLista2;
    private javax.swing.JScrollPane scrPnLista;
    private javax.swing.JTable tableDriver;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtCheckInDate;
    private javax.swing.JTextField txtCheckInTime;
    private javax.swing.JTextField txtCheckOutDate;
    private javax.swing.JTextField txtCheckOutTime;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JLabel txtSaida;
    private javax.swing.JTextField txtSearchSubscriber;
    private javax.swing.JTextField txtSearchUser;
    private javax.swing.JTextField txtVaga;
    // End of variables declaration//GEN-END:variables
}
